// Original code generated by counterfeiter. Modified to meet our needs
package bunny

import (
	"crypto/tls"
	"sync"
)

type fakeDialer struct {
	DialStub        func(string) (amqpConnection, error)
	dialMutex       sync.RWMutex
	dialArgsForCall []struct {
		arg1 string
	}
	dialReturns struct {
		result1 amqpConnection
		result2 error
	}
	dialReturnsOnCall map[int]struct {
		result1 amqpConnection
		result2 error
	}
	DialTLSStub        func(string, *tls.Config) (amqpConnection, error)
	dialTLSMutex       sync.RWMutex
	dialTLSArgsForCall []struct {
		arg1 string
		arg2 *tls.Config
	}
	dialTLSReturns struct {
		result1 amqpConnection
		result2 error
	}
	dialTLSReturnsOnCall map[int]struct {
		result1 amqpConnection
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *fakeDialer) Dial(arg1 string) (amqpConnection, error) {
	fake.dialMutex.Lock()
	ret, specificReturn := fake.dialReturnsOnCall[len(fake.dialArgsForCall)]
	fake.dialArgsForCall = append(fake.dialArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DialStub
	fakeReturns := fake.dialReturns
	fake.recordInvocation("Dial", []interface{}{arg1})
	fake.dialMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *fakeDialer) DialCallCount() int {
	fake.dialMutex.RLock()
	defer fake.dialMutex.RUnlock()
	return len(fake.dialArgsForCall)
}

func (fake *fakeDialer) DialCalls(stub func(string) (amqpConnection, error)) {
	fake.dialMutex.Lock()
	defer fake.dialMutex.Unlock()
	fake.DialStub = stub
}

func (fake *fakeDialer) DialArgsForCall(i int) string {
	fake.dialMutex.RLock()
	defer fake.dialMutex.RUnlock()
	argsForCall := fake.dialArgsForCall[i]
	return argsForCall.arg1
}

func (fake *fakeDialer) DialReturns(result1 amqpConnection, result2 error) {
	fake.dialMutex.Lock()
	defer fake.dialMutex.Unlock()
	fake.DialStub = nil
	fake.dialReturns = struct {
		result1 amqpConnection
		result2 error
	}{result1, result2}
}

func (fake *fakeDialer) DialReturnsOnCall(i int, result1 amqpConnection, result2 error) {
	fake.dialMutex.Lock()
	defer fake.dialMutex.Unlock()
	fake.DialStub = nil
	if fake.dialReturnsOnCall == nil {
		fake.dialReturnsOnCall = make(map[int]struct {
			result1 amqpConnection
			result2 error
		})
	}
	fake.dialReturnsOnCall[i] = struct {
		result1 amqpConnection
		result2 error
	}{result1, result2}
}

func (fake *fakeDialer) DialTLS(arg1 string, arg2 *tls.Config) (amqpConnection, error) {
	fake.dialTLSMutex.Lock()
	ret, specificReturn := fake.dialTLSReturnsOnCall[len(fake.dialTLSArgsForCall)]
	fake.dialTLSArgsForCall = append(fake.dialTLSArgsForCall, struct {
		arg1 string
		arg2 *tls.Config
	}{arg1, arg2})
	stub := fake.DialTLSStub
	fakeReturns := fake.dialTLSReturns
	fake.recordInvocation("DialTLS", []interface{}{arg1, arg2})
	fake.dialTLSMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *fakeDialer) DialTLSCallCount() int {
	fake.dialTLSMutex.RLock()
	defer fake.dialTLSMutex.RUnlock()
	return len(fake.dialTLSArgsForCall)
}

func (fake *fakeDialer) DialTLSCalls(stub func(string, *tls.Config) (amqpConnection, error)) {
	fake.dialTLSMutex.Lock()
	defer fake.dialTLSMutex.Unlock()
	fake.DialTLSStub = stub
}

func (fake *fakeDialer) DialTLSArgsForCall(i int) (string, *tls.Config) {
	fake.dialTLSMutex.RLock()
	defer fake.dialTLSMutex.RUnlock()
	argsForCall := fake.dialTLSArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *fakeDialer) DialTLSReturns(result1 amqpConnection, result2 error) {
	fake.dialTLSMutex.Lock()
	defer fake.dialTLSMutex.Unlock()
	fake.DialTLSStub = nil
	fake.dialTLSReturns = struct {
		result1 amqpConnection
		result2 error
	}{result1, result2}
}

func (fake *fakeDialer) DialTLSReturnsOnCall(i int, result1 amqpConnection, result2 error) {
	fake.dialTLSMutex.Lock()
	defer fake.dialTLSMutex.Unlock()
	fake.DialTLSStub = nil
	if fake.dialTLSReturnsOnCall == nil {
		fake.dialTLSReturnsOnCall = make(map[int]struct {
			result1 amqpConnection
			result2 error
		})
	}
	fake.dialTLSReturnsOnCall[i] = struct {
		result1 amqpConnection
		result2 error
	}{result1, result2}
}

func (fake *fakeDialer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.dialMutex.RLock()
	defer fake.dialMutex.RUnlock()
	fake.dialTLSMutex.RLock()
	defer fake.dialTLSMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *fakeDialer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
