// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
)

type FakeRwLocker struct {
	LockStub        func()
	lockMutex       sync.RWMutex
	lockArgsForCall []struct {
	}
	RLockStub        func()
	rLockMutex       sync.RWMutex
	rLockArgsForCall []struct {
	}
	RUnlockStub        func()
	rUnlockMutex       sync.RWMutex
	rUnlockArgsForCall []struct {
	}
	UnlockStub        func()
	unlockMutex       sync.RWMutex
	unlockArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRwLocker) Lock() {
	fake.lockMutex.Lock()
	fake.lockArgsForCall = append(fake.lockArgsForCall, struct {
	}{})
	stub := fake.LockStub
	fake.recordInvocation("Lock", []interface{}{})
	fake.lockMutex.Unlock()
	if stub != nil {
		fake.LockStub()
	}
}

func (fake *FakeRwLocker) LockCallCount() int {
	fake.lockMutex.RLock()
	defer fake.lockMutex.RUnlock()
	return len(fake.lockArgsForCall)
}

func (fake *FakeRwLocker) LockCalls(stub func()) {
	fake.lockMutex.Lock()
	defer fake.lockMutex.Unlock()
	fake.LockStub = stub
}

func (fake *FakeRwLocker) RLock() {
	fake.rLockMutex.Lock()
	fake.rLockArgsForCall = append(fake.rLockArgsForCall, struct {
	}{})
	stub := fake.RLockStub
	fake.recordInvocation("RLock", []interface{}{})
	fake.rLockMutex.Unlock()
	if stub != nil {
		fake.RLockStub()
	}
}

func (fake *FakeRwLocker) RLockCallCount() int {
	fake.rLockMutex.RLock()
	defer fake.rLockMutex.RUnlock()
	return len(fake.rLockArgsForCall)
}

func (fake *FakeRwLocker) RLockCalls(stub func()) {
	fake.rLockMutex.Lock()
	defer fake.rLockMutex.Unlock()
	fake.RLockStub = stub
}

func (fake *FakeRwLocker) RUnlock() {
	fake.rUnlockMutex.Lock()
	fake.rUnlockArgsForCall = append(fake.rUnlockArgsForCall, struct {
	}{})
	stub := fake.RUnlockStub
	fake.recordInvocation("RUnlock", []interface{}{})
	fake.rUnlockMutex.Unlock()
	if stub != nil {
		fake.RUnlockStub()
	}
}

func (fake *FakeRwLocker) RUnlockCallCount() int {
	fake.rUnlockMutex.RLock()
	defer fake.rUnlockMutex.RUnlock()
	return len(fake.rUnlockArgsForCall)
}

func (fake *FakeRwLocker) RUnlockCalls(stub func()) {
	fake.rUnlockMutex.Lock()
	defer fake.rUnlockMutex.Unlock()
	fake.RUnlockStub = stub
}

func (fake *FakeRwLocker) Unlock() {
	fake.unlockMutex.Lock()
	fake.unlockArgsForCall = append(fake.unlockArgsForCall, struct {
	}{})
	stub := fake.UnlockStub
	fake.recordInvocation("Unlock", []interface{}{})
	fake.unlockMutex.Unlock()
	if stub != nil {
		fake.UnlockStub()
	}
}

func (fake *FakeRwLocker) UnlockCallCount() int {
	fake.unlockMutex.RLock()
	defer fake.unlockMutex.RUnlock()
	return len(fake.unlockArgsForCall)
}

func (fake *FakeRwLocker) UnlockCalls(stub func()) {
	fake.unlockMutex.Lock()
	defer fake.unlockMutex.Unlock()
	fake.UnlockStub = stub
}

func (fake *FakeRwLocker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.lockMutex.RLock()
	defer fake.lockMutex.RUnlock()
	fake.rLockMutex.RLock()
	defer fake.rLockMutex.RUnlock()
	fake.rUnlockMutex.RLock()
	defer fake.rUnlockMutex.RUnlock()
	fake.unlockMutex.RLock()
	defer fake.unlockMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRwLocker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
