// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/streadway/amqp"
)

type FakeAmqpConnection struct {
	ChannelStub        func() (*amqp.Channel, error)
	channelMutex       sync.RWMutex
	channelArgsForCall []struct {
	}
	channelReturns struct {
		result1 *amqp.Channel
		result2 error
	}
	channelReturnsOnCall map[int]struct {
		result1 *amqp.Channel
		result2 error
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	NotifyCloseStub        func(chan *amqp.Error) chan *amqp.Error
	notifyCloseMutex       sync.RWMutex
	notifyCloseArgsForCall []struct {
		arg1 chan *amqp.Error
	}
	notifyCloseReturns struct {
		result1 chan *amqp.Error
	}
	notifyCloseReturnsOnCall map[int]struct {
		result1 chan *amqp.Error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAmqpConnection) Channel() (*amqp.Channel, error) {
	fake.channelMutex.Lock()
	ret, specificReturn := fake.channelReturnsOnCall[len(fake.channelArgsForCall)]
	fake.channelArgsForCall = append(fake.channelArgsForCall, struct {
	}{})
	fake.recordInvocation("Channel", []interface{}{})
	fake.channelMutex.Unlock()
	if fake.ChannelStub != nil {
		return fake.ChannelStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.channelReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAmqpConnection) ChannelCallCount() int {
	fake.channelMutex.RLock()
	defer fake.channelMutex.RUnlock()
	return len(fake.channelArgsForCall)
}

func (fake *FakeAmqpConnection) ChannelCalls(stub func() (*amqp.Channel, error)) {
	fake.channelMutex.Lock()
	defer fake.channelMutex.Unlock()
	fake.ChannelStub = stub
}

func (fake *FakeAmqpConnection) ChannelReturns(result1 *amqp.Channel, result2 error) {
	fake.channelMutex.Lock()
	defer fake.channelMutex.Unlock()
	fake.ChannelStub = nil
	fake.channelReturns = struct {
		result1 *amqp.Channel
		result2 error
	}{result1, result2}
}

func (fake *FakeAmqpConnection) ChannelReturnsOnCall(i int, result1 *amqp.Channel, result2 error) {
	fake.channelMutex.Lock()
	defer fake.channelMutex.Unlock()
	fake.ChannelStub = nil
	if fake.channelReturnsOnCall == nil {
		fake.channelReturnsOnCall = make(map[int]struct {
			result1 *amqp.Channel
			result2 error
		})
	}
	fake.channelReturnsOnCall[i] = struct {
		result1 *amqp.Channel
		result2 error
	}{result1, result2}
}

func (fake *FakeAmqpConnection) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if fake.CloseStub != nil {
		return fake.CloseStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.closeReturns
	return fakeReturns.result1
}

func (fake *FakeAmqpConnection) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeAmqpConnection) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeAmqpConnection) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAmqpConnection) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAmqpConnection) NotifyClose(arg1 chan *amqp.Error) chan *amqp.Error {
	fake.notifyCloseMutex.Lock()
	ret, specificReturn := fake.notifyCloseReturnsOnCall[len(fake.notifyCloseArgsForCall)]
	fake.notifyCloseArgsForCall = append(fake.notifyCloseArgsForCall, struct {
		arg1 chan *amqp.Error
	}{arg1})
	fake.recordInvocation("NotifyClose", []interface{}{arg1})
	fake.notifyCloseMutex.Unlock()
	if fake.NotifyCloseStub != nil {
		return fake.NotifyCloseStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.notifyCloseReturns
	return fakeReturns.result1
}

func (fake *FakeAmqpConnection) NotifyCloseCallCount() int {
	fake.notifyCloseMutex.RLock()
	defer fake.notifyCloseMutex.RUnlock()
	return len(fake.notifyCloseArgsForCall)
}

func (fake *FakeAmqpConnection) NotifyCloseCalls(stub func(chan *amqp.Error) chan *amqp.Error) {
	fake.notifyCloseMutex.Lock()
	defer fake.notifyCloseMutex.Unlock()
	fake.NotifyCloseStub = stub
}

func (fake *FakeAmqpConnection) NotifyCloseArgsForCall(i int) chan *amqp.Error {
	fake.notifyCloseMutex.RLock()
	defer fake.notifyCloseMutex.RUnlock()
	argsForCall := fake.notifyCloseArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAmqpConnection) NotifyCloseReturns(result1 chan *amqp.Error) {
	fake.notifyCloseMutex.Lock()
	defer fake.notifyCloseMutex.Unlock()
	fake.NotifyCloseStub = nil
	fake.notifyCloseReturns = struct {
		result1 chan *amqp.Error
	}{result1}
}

func (fake *FakeAmqpConnection) NotifyCloseReturnsOnCall(i int, result1 chan *amqp.Error) {
	fake.notifyCloseMutex.Lock()
	defer fake.notifyCloseMutex.Unlock()
	fake.NotifyCloseStub = nil
	if fake.notifyCloseReturnsOnCall == nil {
		fake.notifyCloseReturnsOnCall = make(map[int]struct {
			result1 chan *amqp.Error
		})
	}
	fake.notifyCloseReturnsOnCall[i] = struct {
		result1 chan *amqp.Error
	}{result1}
}

func (fake *FakeAmqpConnection) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.channelMutex.RLock()
	defer fake.channelMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.notifyCloseMutex.RLock()
	defer fake.notifyCloseMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAmqpConnection) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
